// examples/react/src/Timer.tsx
import { useStopwatch } from '@watchstop/react'

export function Timer() {
  const { elapsed, start, stop, reset } = useStopwatch()

  return (
    <div className="timer">
      <p className="brand">react</p>
      <p className="elapsed">{Math.floor(elapsed)} ms</p>
      <div className="controls">
        <button type="button" onClick={start}>
          Start
        </button>
        <button type="button" onClick={stop}>
          Stop
        </button>
        <button type="button" onClick={reset}>
          Reset
        </button>
      </div>
    </div>
  )
}

// examples/qwik/src/timer.tsx
import { component$ } from '@qwik.dev/core'
import { useStopwatch } from '@watchstop/qwik'

export const Timer = component$(() => {
  const { elapsed, start, stop, reset } = useStopwatch()

  return (
    <div class="timer">
      <p class="brand">qwik</p>
      <p class="elapsed">{Math.floor(elapsed.value)} ms</p>
      <div class="controls">
        <button type="button" onClick$={start}>
          Start
        </button>
        <button type="button" onClick$={stop}>
          Stop
        </button>
        <button type="button" onClick$={reset}>
          Reset
        </button>
      </div>
    </div>
  )
})
