// examples/react/src/Timer.tsx
import { useState } from 'react'
import { useStopwatch } from '@watchstop/react'

export function Timer() {
  const { elapsed, start, stop, reset } = useStopwatch()
  const [running, setRunning] = useState(false)

  const toggleRun = () => {
    if (running) {
      stop()
      setRunning(false)
      return
    }
    start()
    setRunning(true)
  }

  const resetIdle = () => {
    reset()
    setRunning(false)
  }

  return (
    <div className="timer">
      <p className="brand">react</p>
      <p className="elapsed">{Math.floor(elapsed)} ms</p>
      <div className="controls">
        <button type="button" onClick={toggleRun}>
          {running ? 'Stop' : 'Start'}
        </button>
        <button type="button" onClick={resetIdle}>
          Reset
        </button>
      </div>
    </div>
  )
}

// examples/solid/src/Timer.tsx
import { createSignal } from 'solid-js'
import { useStopwatch } from '@watchstop/solid'

export function Timer() {
  const { elapsed, start, stop, reset } = useStopwatch()
  const [running, setRunning] = createSignal(false)

  const toggleRun = () => {
    if (running()) {
      stop()
      setRunning(false)
      return
    }
    start()
    setRunning(true)
  }

  const resetIdle = () => {
    reset()
    setRunning(false)
  }

  return (
    <div class="timer">
      <p class="brand">solid</p>
      <p class="elapsed">{Math.floor(elapsed())} ms</p>
      <div class="controls">
        <button type="button" onClick={toggleRun}>
          {running() ? 'Stop' : 'Start'}
        </button>
        <button type="button" onClick={resetIdle}>
          Reset
        </button>
      </div>
    </div>
  )
}
