// packages/angular/src/use-store.ts
import type { Store } from '@watchstop/core'
import { DestroyRef, inject, signal, type Signal } from '@angular/core'

export function useStore<T>(store: Store<T>): Signal<T> {
  const latestValue = signal(store.get())
  const unsubscribe = store.subscribe((value) => {
    latestValue.set(value)
  })
  inject(DestroyRef).onDestroy(unsubscribe)
  return latestValue.asReadonly()
}

// packages/react/src/use-store.ts
import { useRef, useSyncExternalStore } from 'react'
import type { Store } from '@watchstop/core'

export function useStore<T>(store: Store<T>): T {
  const snapshot = useRef({ value: store.get() })

  return useSyncExternalStore(
    (onStoreChange): (() => void) => {
      snapshot.current = { value: store.get() }
      return store.subscribe((value) => {
        snapshot.current = { value }
        onStoreChange()
      })
    },
    (): T => snapshot.current.value,
    (): T => store.get(),
  )
}
