// packages/react/src/use-store.ts
import { useRef, useSyncExternalStore } from 'react'
import type { Store } from '@watchstop/core'

export function useStore<T>(store: Store<T>): T {
  const snapshot = useRef({ value: store.get() })

  return useSyncExternalStore(
    (onStoreChange): (() => void) => {
      snapshot.current = { value: store.get() }
      return store.subscribe((value) => {
        snapshot.current = { value }
        onStoreChange()
      })
    },
    (): T => snapshot.current.value,
    (): T => store.get(),
  )
}

// packages/solid/src/use-store.ts
import type { Store } from '@watchstop/core'
import { createSignal, onCleanup, type Accessor } from 'solid-js'

export function useStore<T>(store: Store<T>): Accessor<T> {
  const [readValue, setValue] = createSignal(store.get())
  onCleanup(
    store.subscribe((value) => {
      setValue(() => value)
    }),
  )
  return readValue
}
